import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {motionPreference,resolveMotionMode} from "../assets/js/core/motion-policy.js";
const root=resolve(import.meta.dirname,".."),read=path=>readFileSync(resolve(root,path),"utf8");
assert.equal(resolveMotionMode({preference:"creative"}),"creative");
assert.equal(resolveMotionMode({preference:"creative",reduced:true}),"off");
assert.equal(resolveMotionMode({preference:"creative",saveData:true}),"lite");
assert.equal(resolveMotionMode({preference:"creative",hardwareConcurrency:4}),"lite");
assert.equal(resolveMotionMode({preference:"off"}),"off");assert.equal(motionPreference("unexpected"),"creative");
const vendor=read("assets/vendor/animejs/anime.esm.min.js").replace(/\r\n/g,"\n");
assert.equal(createHash("sha256").update(vendor).digest("hex"),"f11a30625dd64df25bea297dc20c20cb22ac2e701a8196ecfe7a2ae5213fd5eb");
const html=read("index.html"),motion=read("assets/js/modules/motion.js"),menu=read("assets/js/modules/hybrid-menu.js"),css=read("assets/css/motion.css"),worker=read("service-worker.js"),license=read("assets/vendor/animejs/LICENSE.md");
for(const token of ["motionToggle","aria-pressed","assets/css/motion.css"])assert(html.includes(token),`Controlo visual em falta: ${token}`);
assert(menu.includes("data-motion-toggle")&&menu.includes("distak:motion-controls"),"O telemóvel precisa do mesmo controlo de movimento.");
for(const token of ["anime.esm.min.js","prefers-reduced-motion","forced-colors","saveData","hardwareConcurrency","distak:view-change","distak:assistant-open","distak:assistant-message","clean()"] )assert(motion.includes(token),`Camada Anime.js incompleta: ${token}`);
for(const forbidden of ["loop:true","exec-stat strong","statValorContratado","input[type","button[type=submit"] )assert(!motion.includes(forbidden),`Animação proibida em área crítica: ${forbidden}`);
assert(css.includes("prefers-reduced-motion:reduce")&&css.includes("forced-colors:active"));
assert(worker.includes("assets/vendor/animejs/anime.esm.min.js")&&worker.includes("assets/js/modules/motion.js")&&worker.includes("assets/css/motion.css"));
assert(license.includes("MIT License")&&license.includes("Julian Garnier"));
console.log("Anime.js aprovado: v4.4.1 local e íntegra, modo criativo reversível, redução de movimento, modo leve e áreas críticas protegidas.");
